[package]
name = "txflow"
version = "0.0.1"
authors = ["Near Inc <hello@nearprotocol.com>"]

[dependencies]
primitives = { path = "../primitives" }
typed-arena = "1.4.1"
futures = "0.1.25"
tokio = "0.1"
rand = "0.6.0"
chrono = "0.4.6"
