image: node:10

variables:
  NODE_ENV: ci
  NEARCORE_DIR: nearcore

stages:
  - build
  - test

cache:
  paths:
    - nearcore/
    - node_modules/

install_dependencies:
  stage: build
  script:
    - git clone --depth 1 https://github.com/nearprotocol/nearcore.git nearcore
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: npm test

lint:
  stage: test
  script: npm run lint
