[package]
name = "nearcore"
version = "0.0.1"
authors = ["Near Inc <hello@nearprotocol.com>"]

[[bin]]
name = "nearcore"
path = "node/src/main.rs"

[dependencies]
node-cli = { path = "./node/cli" }
node-runtime = { path = "./node/runtime" }

[workspace]
members = [
    "core/primitives",
    "core/storage",
    "core/txflow",
    "core/wasm",
    "core/wasm/runtest",
    "core/beacon",
    "node/cli",
    "node/runtime",
    "node/service",
    "node/network",
    "test-utils/node"
]
