[[bin]]
name = "nearcore"
path = "src/main.rs"

[package]
name = "nearcore"
version = "0.0.1"
authors = ["Near Inc <hello@nearprotocol.com>"]

[dependencies]
futures = "0.1"
tokio = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
env_logger = "0.5"
parking_lot = "0.6"

libp2p = { git = "https://github.com/tomaka/libp2p-rs", rev = "8111062f0177fd7423626f2db9560273644a4c4d", default-features = false, features = ["libp2p-secio", "libp2p-secio-secp256k1"] }
substrate-network-libp2p = { path = "core/network-libp2p" }
primitives = { path = "core/primitives" }
network = { path = "core/network" }
storage = { path = "core/storage" }
runtime = { path = "core/runtime" }
client = { path = "core/client" }


[workspace]
members = [
    "core/primitives",
    "core/network",
    "core/storage",
    "core/runtime",
    "core/client",
]
