[package]
name = "network"
version = "0.0.1"
authors = ["Near Inc <hello@nearprotocol.com>"]

[dependencies]
futures = "0.1"
tokio = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bytes = "0.2"
parking_lot = "0.6"
log = "0.4"

substrate-network-libp2p = { path = "../../core/network-libp2p" }
primitives = { path = "../../core/primitives" }

[dependencies.bincode]
version = "1.0"
features = ["i128"]
